services:
  front:
      build:
        context: .
      ports:
        - "5173:5173"
      volumes:
        - .:/app
        - ./node_modules:/app/node_modules
      environment:
        NODE_ENV: dev
      command: npm run dev
      stdin_open: true
      tty: true
      networks:
        - alerta-risk-net

networks:
  alerta-risk-net:
    name: alerta-risk-net