services:
  front:
    build: .
    command: npm run dev
    container_name: alertarisk-front
    restart: always
    ports:
      - "3000:3000"
    volumes:
    - .:/app
    - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    networks:
          - alerta-risk-net

networks:
  alerta-risk-net:
    name: alerta-risk-net